version: '3.8'
services:
  chat_js:
    build: .
    #Descomentar la siguiente linea si se desea hacer que funcione con nodemon. Recuerde abrir el archivo Dockerfile y quitar la bandera --production del comando npm install --production
    #command: npm run dev
    image: chat_js:latest
    container_name: chat_js
    ports:
      - 3000:3000
    volumes:
      - .:/chat_js